on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+

name: APK Builder

jobs:
  v3_13:
    name: v3.13
    runs-on: ubuntu-20.04
    env:
      ALPINE_VERSION: v3.13
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: GHCR Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build
        run: |
          make -C ${{ env.ALPINE_VERSION }} build
      -
        name: Push
        run: |
          make -C ${{ env.ALPINE_VERSION }} push
